name: Deploy AWS Infrastructure with Terraform

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Generate Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Generate Markdown with Terraform Docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          output-file: README.md
          output-method: inject
          config-file: .terraform-docs.yml

      - name: Apply Terraform on Merge
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  terraform-docs:
    name: Generate Terraform Docs for PRs
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Markdown with Terraform Docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          output-file: README.md
          output-method: inject
          config-file: .terraform-docs.yml

      - name: Create Pull Request Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              body: 'Terraform Docs have been updated. Please review the changes.'
            })
